/**
 * Content resources — the catalogue side of the site. Each one is a plain
 * CRUD collection generated by lib/crudFactory and mounted with the same
 * verb→guard→handler shape:
 *   GET  /<path>        public  list (search/filter/range/sort/paginate)
 *   GET  /<path>/:id    public  one (by ObjectId OR slug)
 *   POST/PATCH/DELETE   admin   write
 *
 * Translatable text is stored as { en, bn } so the bilingual frontend can pick.
 */
const express = require("express");
const { verifyJWT, verifyRole } = require("../middlewares/auth");
const { makeCrud } = require("../lib/crudFactory");

const router = express.Router();
const admin = [verifyJWT, verifyRole("super-admin")];

// Mount the 5 standard CRUD endpoints for a resource in one call.
function mountCrud(path, collection, opts) {
  const c = makeCrud(collection, opts);
  router.get(`/${path}`, c.list);
  router.get(`/${path}/:id`, c.getOne);
  router.post(`/${path}`, ...admin, c.create);
  router.patch(`/${path}/:id`, ...admin, c.update);
  router.delete(`/${path}/:id`, ...admin, c.remove);
}

// ── Tour packages ─────────────────────────────────────────
mountCrud("packages", "packages", {
  searchFields: ["title.en", "title.bn", "summary.en", "location.en"],
  filterFields: ["type", "destinationId", "featured", "status"],
  rangeParam: { param: "price", field: "price.amount" },
  slugFrom: "title.en",
  requiredFields: ["title.en"],
});

// ── Destinations ──────────────────────────────────────────
mountCrud("destinations", "destinations", {
  searchFields: ["name.en", "name.bn", "country"],
  filterFields: ["country", "popular", "status"],
  slugFrom: "name.en",
  requiredFields: ["name.en"],
});

// ── Hajj & Umrah packages ─────────────────────────────────
mountCrud("hajj", "hajj", {
  searchFields: ["title.en", "title.bn"],
  filterFields: ["type", "packageClass", "status"], // type: hajj | umrah
  rangeParam: { param: "price", field: "price.amount" },
  slugFrom: "title.en",
  requiredFields: ["title.en"],
});

// ── Visa services ─────────────────────────────────────────
mountCrud("visas", "visas", {
  searchFields: ["country", "title.en"],
  filterFields: ["country", "visaType", "status"],
  slugFrom: "title.en",
  requiredFields: ["title.en"],
});

// ── Hotels ────────────────────────────────────────────────
mountCrud("hotels", "hotels", {
  searchFields: ["name.en", "name.bn", "city", "country"],
  filterFields: ["city", "country", "rating", "status"],
  rangeParam: { param: "price", field: "price.amount" },
  slugFrom: "name.en",
  requiredFields: ["name.en"],
});

// ── Air-ticket featured fares / routes (requests funnel via /inquiries) ──
mountCrud("air-tickets", "airtickets", {
  searchFields: ["from", "to", "airline"],
  filterFields: ["from", "to", "airline", "tripType", "status"],
  rangeParam: { param: "price", field: "price.amount" },
  requiredFields: ["from", "to"],
});

// ── Home banners / sliders ────────────────────────────────
mountCrud("banners", "banners", {
  filterFields: ["position", "active"],
  defaultSort: { order: 1 },
});

// ── Coupons / discounts ───────────────────────────────────
mountCrud("coupons", "coupons", {
  filterFields: ["active"],
  requiredFields: ["code"],
});

module.exports = router;
